### ISSUE TITLE
Source code link broken

### ISSUE THREAD

**Issue by gregbenner** [patr0nus/DeskGap#63]
"API Demos
The DeskGap API Demos app shows some of the DeskGap features and APIs with interactive scripts."
source code links to https://github.com/patr0nus/DeskGap/tree/master/app it should maybe point to this instead? https://github.com/patr0nus/DeskGap/tree/master/node/app

**Comment by gregbenner** [comment]
Side not that node/app example seems broken
``` eskgap ./main.js

Uncaught exception TypeError: mainWindow.webView.publishServices is not a function
    at p.<anonymous> (/home/gnb/Sites/DeskGap-master/node/app/main.js:18:22)
    at Object.onceWrapper (events.js:300:26)
    at p.emit (events.js:210:5)
    at p.trigger_ (nod.entry:1:1333)
    at onReady (nod.entry:1:2493)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deskgap-default-app@ start: `deskgap ./main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deskgap-default-app@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gnb/.npm/_logs/2020-07-12T22_00_03_368Z-debug.log
The terminal process terminated with exit code: 1```
