### ISSUE TITLE
Installing on Ubuntu 20.04 LTS fails

### ISSUE THREAD

**Issue by ElyaConrad** [patr0nus/DeskGap#73]
I'm trying to install `deskgap` from scratch on Ubuntu 20.04. but the `npm install` already fails during the installation script.

```bash
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /home/maurice/Dokumente/Beruf/creactive/Bluepic/toolpic-editor/node_modules/deskgap
npm ERR! command failed
npm ERR! command sh -c node install.js
Downloading deskgap-v0.2.0-linux-x64.zip
npm ERR! Error: GET https://dl.bintray.com/patr0nus/DeskGap/deskgap-v0.2.0-linux-x64.zip returned 403
npm ERR! Error: GET https://dl.bintray.com/patr0nus/DeskGap/deskgap-v0.2.0-linux-x64.zip returned 403
npm ERR!     at Request.<anonymous> (/home/maurice/Dokumente/Beruf/creactive/Bluepic/toolpic-editor/node_modules/nugget/index.js:169:61)
npm ERR!     at Request.emit (node:events:369:20)
npm ERR!     at Request.onRequestResponse (/home/maurice/Dokumente/Beruf/creactive/Bluepic/toolpic-editor/node_modules/request/request.js:1059:10)
npm ERR!     at ClientRequest.emit (node:events:369:20)
npm ERR!     at HTTPParser.parserOnIncomingClient (node:_http_client:646:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:129:17)
npm ERR!     at TLSSocket.socketOnData (node:_http_client:512:22)
npm ERR!     at TLSSocket.emit (node:events:369:20)
npm ERR!     at addChunk (node:internal/streams/readable:313:12)
npm ERR!     at readableAddChunk (node:internal/streams/readable:288:9)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/maurice/.npm/_logs/2021-05-06T09_44_51_461Z-debug.log

```

This looks like an iussue not just with the system's version but with the sources that throw a `403`

**Comment by navidmafi** [comment]
![image](https://user-images.githubusercontent.com/46371349/118504755-0c2d8880-b741-11eb-9777-47dd6da1d1d8.png)
same here in windows
i recommend changing title to something like "Installation source returns 403 error"

**Comment by nwesterhausen** [comment]
This is happening because Bintray is sunsetting. I visited [https://bintray.com/patr0nus/DeskGap](https://bintray.com/patr0nus/DeskGap) to look for any hints on the 403.

> Thanks for supporting Bintray! This service has now been sunset, and to assist with migration to the JFrog Platform, paid accounts can login until July 4th.

**Comment by RockyF** [comment]
download bintray from github release page, and set an env variable which named `DESKGAP_DIST_FOLDER` to value `your bintray folder`, not bintray file path
then install deskgap!
enjoy!

**Comment by samuelscheit** [comment]
> download bintray from github release page, and set an env variable which named `DESKGAP_DIST_FOLDER` to value `your bintray folder`, not bintray file path

is there any other easier way?

**Comment by RockyF** [comment]
> is there any other easier way?

yes, download npm package in release page, and modify install script in package.json, link npm package to your pc, then 
 install this package.  
enjoy!  
forgive my poor english!😭

**Comment by wtesler** [comment]
Why is this so difficult? Basically the installation is totally broken and that's the real problem. The solutions above are just weird bandaids. Is this project still active at all?
