### ISSUE TITLE
Doesn't install. I get errors.

### ISSUE THREAD

**Issue by Babyyoda777** [patr0nus/DeskGap#76]
C:\Users\azlan>npm install deskgap
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

> deskgap@0.2.0 postinstall C:\Users\azlan\node_modules\deskgap
> node install.js

Downloading deskgap-v0.2.0-win32-ia32.zip
Error: GET https://dl.bintray.com/patr0nus/DeskGap/deskgap-v0.2.0-win32-ia32.zip returned 403
Error: GET https://dl.bintray.com/patr0nus/DeskGap/deskgap-v0.2.0-win32-ia32.zip returned 403
    at Request.<anonymous> (C:\Users\azlan\node_modules\nugget\index.js:169:61)
    at Request.emit (events.js:376:20)
    at Request.onRequestResponse (C:\Users\azlan\node_modules\request\request.js:1059:10)
    at ClientRequest.emit (events.js:376:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:376:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\azlan\package.json'
npm WARN azlan No description
npm WARN azlan No repository field.
npm WARN azlan No README data
npm WARN azlan No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deskgap@0.2.0 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deskgap@0.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\azlan\AppData\Roaming\npm-cache\_logs\2021-06-06T18_19_54_847Z-debug.log

**Comment by navidmafi** [comment]
please check other issues first, before opening new one
https://github.com/patr0nus/DeskGap/issues/73#issuecomment-853504942
also use ``` code blocks ``` to paste log
